language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
matrix:
  allow_failures:
    - node_js: "iojs"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g karma-cli
  - npm install -g bower
  - npm install codecov.io jasmine-core karma karma-chrome-launcher karma-coverage karma-firefox-launcher karma-jasmine
  - bower install

script:
  - karma start --no-auto-watch --single-run --browsers Firefox


after_success:
  cat ./coverage/*/lcov.info | ./node_modules/.bin/codecov