language: node_js
node_js:
  - "0.12"
  - "0.10"
  - io.js

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g karma-cli
  - npm install -g bower
  - npm install
  - bower install

script:
  - karma start --no-auto-watch --single-run --browsers Firefox

after_success:
  cat ./coverage/*/lcov.info | ./node_modules/.bin/codecov